import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useRef, useState} from "react";
import Web3Modal from 'web3modal';


const inter = Inter({subsets: ['latin']})

export default function Home() {
    const [walletConnected, setWalletConnected] = useState(false);
    const web3ModalRef = useRef();

    const getProviderOrSigner = async (needSigner = false) => {
        const provider = await web3ModalRef.current.connect();
        const web3Provider = new ethers.providers.Web3Provider(provider);
        const {chainId} = await web3Provider.getNetwork();
        if (chainId != 97) {
            window.alert("Change to BNBchain test Net");
        }
        if (needSigner) {
            const signer = web3Provider.getSigner();
            return signer;
        }
        return web3Provider;
    }

    const connectWallet = async () => {
        try {
            await getProviderOrSigner();
            setWalletConnected(true);
        } catch (error) {
            console.log(error)
        }
    }

    const renderButton = () => {
        if (walletConnected) {
            return (
                <div>
                    <h4>Success</h4>
                    <button className={styles.button}>PressMeButton</button>
                </div>
            )
        }
    }

    useEffect(() => {
        if (!walletConnected) {
            web3ModalRef.current = new Web3Modal({
                network: 97,
                providerOptions: {},
                disableInjectedProvider: false
            })
        }
    }, [walletConnected]);


    return (
        <>
            <Head>
                <title>ANANAS SYSTEM LTD.</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        Ananas Document Signer
                    </p>
                    <div>
                        <button onClick={connectWallet} className={styles.button}>
                            {!walletConnected ? "Connect Wallet" : "disconnect"}
                        </button>
                    </div>
                </div>
                <div>
                    {renderButton()}
                    <p>You can sign doc</p>
                </div>

            </main>
        </>
    )
}
